config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
  	root "dashboard#index"
  end

  namespace :admins do
		resources :campaigns do
			resources :pages
		end
  end

  resources :campaigns do
    resources :pages
  end

  root "home#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@campaigns = current_admin.campaigns
	end
end

app/views/dashboard/index.html.erb
<br>
<div id="admin-dashboard-index">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<header>
					<h3>Dashboard for <%= current_admin.company %></h3>
				</header>
			</div>
		</div>
	</div>

	<br>

	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<div class="admin-campaigns-wrapper">
					<h5>Your campaigns</h5>
					<ul class="list-group">
						<% @campaigns.each do |campaign| %>
							<li class="list-group-item justify-content-between">
								<%= link_to "#{campaign.name}", admins_campaign_path(campaign) %>
								<% if campaign.active? %>
									<span class="badge badge-default badge-pill badge-success">Active</span>
								<% else %>
									<span class="badge badge-default badge-pill badge-danger">Inactive</span>
								<% end %>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<br>

	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<%= link_to "New campaign", new_admins_campaign_path, class: "btn btn-md btn-primary" %>
			</div>
		</div>
	</div>
</div>