config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
  	root "dashboard#index"
  end

  namespace :admins do
		resources :campaigns do
			resources :pages
		end
  end

  resources :campaigns do
    resources :pages
  end

  root "home#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :campaigns
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :admin
  has_many :pages, dependent: :destroy

  validates :name, :title, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :campaign
  has_attached_file :button_photo

  validates :title, presence: true
  validates_attachment_content_type :button_photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/admins/campaigns_controller.rb
class Admins::CampaignsController < AdminsController
	# before_action :restrict_permissions, only: [:show, :edit]

	def new
		@campaign = current_admin.campaigns.new	
	end

	def create
		@campaign = current_admin.campaigns.new(campaign_params)
		if @campaign.save
			flash[:notice] = "New campaign is created."
			redirect_to root_url
		else
			flash[:alert] = "Couldn't create new campaign."
			render :new
		end
	end

	def show
		@campaign = Campaign.find(params[:id])
	end

	def edit
		@campaign = Campaign.find(params[:id])
	end

	def update
		@campaign = current_admin.campaigns.find(params[:id])
		if @campaign.update_attributes(campaign_params)
			flash[:notice] = "Campaign is updated."
			redirect_to admins_campaign_url(@campaign)
		else
			flash[:alert] = "Couldn't update campaign."
			render :new
		end
	end

	def destroy
		@campaign = Campaign.find(params[:id])
		if @campaign.destroy
			flash[:notice] = "Campaign deleted."
			redirect_to root_path
		end
	end

	private
	def restrict_permissions
		@campaign = Campaign.find(params[:id])
		unless current_admin.id == @campaign.admin_id
      flash[:alert] = "You don't have access to that."
      redirect_to root_url
    end
	end

	def campaign_params
		params.require(:campaign).permit(:url, :title, :description, :active, :name)
	end
end

app/controllers/admins/confirmations_controller.rb
class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/pages_controller.rb
class Admins::PagesController < AdminsController
	before_action :set_campaign, only: [:new, :create, :show, :edit, :update, :destroy]
	# before_action :restrict_permissions, only: [:show, :edit]

	def new
		@page = @campaign.pages.new
	end

	def create
		@page = @campaign.pages.new(page_params)
		if @page.save
			flash[:notice] = "New page is created."
			redirect_to admins_campaign_url(@campaign)
		else
			flash[:alert] = "Couldn't create page."
			render :new
		end
	end

	def show
		@page = Page.find(params[:id])
	end

	def edit
		@page = @campaign.pages.find(params[:id])
	end

	def update
		@page = @campaign.pages.find(params[:id])
		if @page.update_attributes(page_params)
			flash[:notice] = "Page is updated."
			redirect_to admins_campaign_url(@campaign)
		else
			flash[:alert] = "Couldn't update page."
			render :new
		end
	end

	def destroy
		@page = @campaign.pages.find(params[:id])
		if @page.destroy
			flash[:notice] = "Page is deleted."
			redirect_to admins_campaign_url(@campaign)
		end
	end

	private
	def set_campaign
		@campaign = Campaign.find(params[:campaign_id])
	end

	def restrict_permissions
		@campaign = Campaign.find(params[:campaign_id])
		unless current_admin.id == @campaign.admin_id
      flash[:alert] = "You don't have access to that."
      redirect_to root_url
    end
	end

	def page_params
		params.require(:page).permit(:title, :content, :url, :page_type, :button_photo)
	end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_admin!
  before_action :configure_permitted_parameters, if: :devise_controller?

	def disable_nav
	  @disable_nav = true
	end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:company, :website])
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :disable_nav, only: [:show]

	def show
		@campaign = Campaign.find(params[:id])
		@pages = @campaign.pages
		validate_campaign
	end

	private
	def validate_campaign
		if !@campaign.active?
			redirect_to "http://#{@campaign.admin.website}"
		elsif @campaign.url.present?
			redirect_to "http://#{@campaign.url}"
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
		@campaigns = current_admin.campaigns
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :disable_nav, only: [:show]

	def show
		@campaign = Campaign.find(params[:campaign_id])
		@page = Page.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/admins/pages/_form.html.erb
<%= render "admins/partials/error_messages", item: @page %>
<%= form_for [:admins, @campaign, @page], html: { multipart: true } do |f| %>
	<div class="form-group">
		<%= f.label :page_type %>
		<%= f.select :page_type, ['content', 'uri', 'url', 'email', 'phone'], {}, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :url, "URL, URI, email or phonenumber" %>
		<p style="font-size: 12px;">Do not use http when using url/uri. Example: facebook.com or www.facebook.com</p>
		<%= f.text_field :url, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :title, "Title (displayed as the button)" %>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :button_photo %><br>
		<%= f.file_field :button_photo %>
	</div>

	<div class="form-group">
		<%= f.label :content, "Content (applies only if type content is selected)" %>
		<p style="font-size: 12px;">Content will be shown for users when they click the page, but only if content is selected as the page type.</p>
		<%= f.text_area :content, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-md btn-primary" %>
	</div>
<% end %>

app/views/admins/pages/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<h2>Edit page <%= @page.title %></h2>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/admins/pages/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<h4>New page for <b><%= @campaign.title %></b></h4>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/admins/pages/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<ul>
				<li>Page type: <%= @page.page_type %></li>
				<li>URL: <%= @page.url %></li>
				<li>Title: <%= @page.title %></li>
				<li>Content: <%= @page.content %></li>
			</ul>
			<%= link_to "Edit", edit_admins_campaign_page_path(@campaign, @page), class: "btn btn-md btn-secondary" %>
		</div>
	</div>
</div>

app/views/admins/partials/_error_messages.html.erb
<% if item.errors.any? %>
	<% item.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_flash_messages.html.erb
<% if alert %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 25px;">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	  </button>
	  <strong>Ups!</strong> <%= flash[:alert] %>
	</div>
<% elsif notice %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
  	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	<span aria-hidden="true">&times;</span>
  	</button>
  	<strong>Success!</strong> <%= flash[:notice] %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Trickle", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if admin_signed_in? %>
        <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "btn btn-link my-2 my-sm-0" %>
      <% else %>
        <%= link_to "Sign in", new_admin_session_path, class: "btn btn-link my-2 my-sm-0" %>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trickle</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
  	<%= render "layouts/navigation" unless @disable_nav %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= render "layouts/flash_messages" %>
        </div>
      </div>
    </div>
  	<%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<div id="users-page-show">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<%= @page.content %>
			</div>
		</div>
	</div>
</div>