config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
  	root "dashboard#index"
  end

  namespace :admins do
		resources :campaigns do
			resources :pages
		end
  end

  resources :campaigns do
    resources :pages
  end

  root "home#index"

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :admin
  has_many :pages, dependent: :destroy

  validates :name, :title, presence: true
end

app/controllers/admins/campaigns_controller.rb
class Admins::CampaignsController < AdminsController
	# before_action :restrict_permissions, only: [:show, :edit]

	def new
		@campaign = current_admin.campaigns.new	
	end

	def create
		@campaign = current_admin.campaigns.new(campaign_params)
		if @campaign.save
			flash[:notice] = "New campaign is created."
			redirect_to root_url
		else
			flash[:alert] = "Couldn't create new campaign."
			render :new
		end
	end

	def show
		@campaign = Campaign.find(params[:id])
	end

	def edit
		@campaign = Campaign.find(params[:id])
	end

	def update
		@campaign = current_admin.campaigns.find(params[:id])
		if @campaign.update_attributes(campaign_params)
			flash[:notice] = "Campaign is updated."
			redirect_to admins_campaign_url(@campaign)
		else
			flash[:alert] = "Couldn't update campaign."
			render :new
		end
	end

	def destroy
		@campaign = Campaign.find(params[:id])
		if @campaign.destroy
			flash[:notice] = "Campaign deleted."
			redirect_to root_path
		end
	end

	private
	def restrict_permissions
		@campaign = Campaign.find(params[:id])
		unless current_admin.id == @campaign.admin_id
      flash[:alert] = "You don't have access to that."
      redirect_to root_url
    end
	end

	def campaign_params
		params.require(:campaign).permit(:url, :title, :description, :active, :name)
	end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :disable_nav, only: [:show]

	def show
		@campaign = Campaign.find(params[:id])
		@pages = @campaign.pages
		validate_campaign
	end

	private
	def validate_campaign
		if !@campaign.active?
			redirect_to "http://#{@campaign.admin.website}"
		elsif @campaign.url.present?
			redirect_to "http://#{@campaign.url}"
		end
	end
end

app/views/campaigns/_pages_links.html.erb
<% @pages.each do |page| %>
	<% if page.button_photo.present? %>
		<div id="page-item-background-button" style="background-image: url(<%= page.button_photo.url %>);">
			<%= link_to "#{page.title}", "http://#{page.url}", class: "" if page.page_type == "url" %>
			<%= link_to "#{page.title}", "#{page.url}", class: "" if page.page_type == "uri" %>
			<%= mail_to "#{page.url}", "#{page.title}", class: "" if page.page_type == "email" %>
			<%= link_to "#{page.title}", "tel:#{page.url}", class: "" if page.page_type == "phone" %>
			<%= link_to "#{page.title}", campaign_page_path(@campaign, page), class: "" if page.page_type == "content" %>
		</div>
	<% else %>
		<div class="page-item-no-background">
			<%= link_to "#{page.title}", "http://#{page.url}", class: "btn btn-lg btn-primary btn-block" if page.page_type == "url" %>
			<%= link_to "#{page.title}", "#{page.url}", class: "btn btn-lg btn-primary btn-block" if page.page_type == "uri" %>
			<%= mail_to "#{page.url}", "#{page.title}", class: "btn btn-lg btn-primary btn-block" if page.page_type == "email" %>
			<%= link_to "#{page.title}", "tel:#{page.url}", class: "btn btn-lg btn-primary btn-block" if page.page_type == "phone" %>
			<%= link_to "#{page.title}", campaign_page_path(@campaign, page), class: "btn btn-lg btn-primary btn-block" if page.page_type == "content" %>
		</div>
	<% end %>
<% end %> 

app/views/campaigns/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div id="users-pages-index">
				<header>
					<h2><%= @campaign.title %></h2>
					<p><%= @campaign.description %></p>
				</header>
				
				<div class="users-pages-wrapper">
					<%= render "pages_links" %>
				</div>
			</div>
		</div>
	</div>
</div>