config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
  	root "dashboard#index"
  end

  namespace :admins do
		resources :campaigns do
			resources :pages
		end
  end

  resources :campaigns do
    resources :pages
  end

  root "home#index"

end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :admin
  has_many :pages, dependent: :destroy

  validates :name, :title, presence: true
end

app/controllers/admins/campaigns_controller.rb
class Admins::CampaignsController < AdminsController
	# before_action :restrict_permissions, only: [:show, :edit]

	def new
		@campaign = current_admin.campaigns.new	
	end

	def create
		@campaign = current_admin.campaigns.new(campaign_params)
		if @campaign.save
			flash[:notice] = "New campaign is created."
			redirect_to root_url
		else
			flash[:alert] = "Couldn't create new campaign."
			render :new
		end
	end

	def show
		@campaign = Campaign.find(params[:id])
	end

	def edit
		@campaign = Campaign.find(params[:id])
	end

	def update
		@campaign = current_admin.campaigns.find(params[:id])
		if @campaign.update_attributes(campaign_params)
			flash[:notice] = "Campaign is updated."
			redirect_to admins_campaign_url(@campaign)
		else
			flash[:alert] = "Couldn't update campaign."
			render :new
		end
	end

	def destroy
		@campaign = Campaign.find(params[:id])
		if @campaign.destroy
			flash[:notice] = "Campaign deleted."
			redirect_to root_path
		end
	end

	private
	def restrict_permissions
		@campaign = Campaign.find(params[:id])
		unless current_admin.id == @campaign.admin_id
      flash[:alert] = "You don't have access to that."
      redirect_to root_url
    end
	end

	def campaign_params
		params.require(:campaign).permit(:url, :title, :description, :active, :name)
	end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
	before_action :disable_nav, only: [:show]

	def show
		@campaign = Campaign.find(params[:id])
		@pages = @campaign.pages
		validate_campaign
	end

	private
	def validate_campaign
		if !@campaign.active?
			redirect_to "http://#{@campaign.admin.website}"
		elsif @campaign.url.present?
			redirect_to "http://#{@campaign.url}"
		end
	end
end

app/views/admins/campaigns/_form.html.erb
<%= render "admins/partials/error_messages", item: @campaign %>
<%= form_for [:admins, @campaign] do |f| %>
	<div class="form-group">
		<%= f.label :url, "URL (filling out this will always redirect users to the selected URL if campaign is active.
		Remove any http. Example: facebook.com or www.facebook.com)" %>
		<%= f.text_field :url, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :name, "Campaign name (not visible to users)" %>
		<p style="font-size: 12px;">Choose a suitable name for this unit. Example: "Practical information."</p>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :title, "Heading (visible on landing page)" %>
		<p style="font-size: 12px;">example: "Hva kan vi hjelpe deg med?"</p>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description, "Description (visible on landing page)" %>
		<p style="font-size: 12px;">Optional if you want to provide more info.</p>
		<%= f.text_area :description, class: "form-control" %>
	</div>

  <%= f.label :active, "Active", :value => "true"  %>
  <%= f.radio_button :active, true %>

  <%= f.label :active, "Not active", :value => "false" %>
  <%= f.radio_button :active, false %>

	<div class="form-group">
		<%= f.submit class: "btn btn-md btn-primary" %>
	</div>
<% end %>

app/views/admins/campaigns/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<h2>Edit <%= @campaign.name %></h2>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/admins/campaigns/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
				<h2>New campaign</h2>
			<%= render "form" %>
		</div>
	</div>
</div>

app/views/admins/campaigns/show.html.erb
<br>

<div class="container">
	<div class="row">
		<div class="col-lg-12">

			<div class="row">
				<div class="col-lg-6">
			  	<h3 class="card-title"><%= @campaign.name %></h3>
		    	<div class="card">
		      	<div class="card-block">
			        <p class="card-text">Heading: <%= @campaign.title %></p>
			        <p class="card-text">Description: <%= @campaign.description %></p>
			        <p class="card-text">Active: <%= @campaign.active %></p>
			        <p class="card-text">Currently <%= pluralize(@campaign.pages.count, "page") %></p>
					    <%= link_to "Edit", edit_admins_campaign_path(@campaign), class: "btn btn-secondary" %>
					    <%= link_to "Add page", new_admins_campaign_page_path(@campaign), class: "btn btn-primary" %>
					    <%= link_to "Simulate user", campaign_path(@campaign), class: "btn btn-md btn-success" %>
					    <%= link_to "Delete", admins_campaign_path(@campaign), class: "btn btn-md btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete campaign #{@campaign.name}? This action is irreversable and will delete every pages associated with the campaign." } %>
					  </div>
					</div>
					<br>
				</div>

				<div class="col-lg-6">
					<h3 class="card-title">Pages</h3>
					<% if @campaign.pages.any? %>
						<ul class="list-group">
							<% @campaign.pages.each do |page| %>
					  		<li class="list-group-item justify-content-between">
					  			<%= link_to "#{page.title}", admins_campaign_page_path(@campaign, page) %>
					  			<%= link_to "Delete", admins_campaign_page_path(@campaign, page), method: :delete, data: { confirm: "Are you sure you want to delete #{page.title}? This action is irreversable." } %>
					  		</li>
							<% end %>
						</ul>
					<% else %>
						<p>You haven't added any pages to this campaign yet.</p>
					<% end %>
				</div>
			</div>

		</div>
	</div>
</div>